(eval-when-compile
  (require 'color-theme))

(defun color-theme-nino ()
  "Example theme. Carbon copy of color-theme-gnome contributed by Jonadab."
 (interactive)
  (color-theme-install
   '(color-theme-nino
     ((font . "fixed")
      (width . 130)
      (height . 50)
      (background-color . "black")
      ;;(background-color . "grey8")
      ;;(foreground-color . "grey85")
      (foreground-color . "snow")
      (background-mode . dark)
      (mouse-color . "grey85")
      (cursor-color . "grey85"))
     (default ((t (nil))))
     ;;(font-lock-comment-face ((t (:italic t :foreground "grey60"))))
     (font-lock-comment-face ((t (:italic t :foreground "brown1"))))
     ;;(font-lock-string-face ((t (:foreground "Magenta"))))
     (font-lock-string-face ((t (:foreground "yellow2"))))
     (font-lock-keyword-face ((t (:foreground "Cyan"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink"))))
     ;;(font-lock-constant-face ((t (:foreground "OliveDrab"))))
     (font-lock-constant-face ((t (:foreground "Magenta"))))
     (font-lock-type-face ((t (:foreground "light sea green"))))
     (font-lock-variable-name-face ((t (:foreground "DarkGoldenrod3"))))
     ;;(font-lock-function-name-face ((t (:foreground "SlateBlue1"))))
     (font-lock-function-name-face ((t (:foreground "MediumPurple1"))))
     (font-lock-builtin-face ((t (:foreground "light sky blue"))))
     (highline-face ((t (:background "grey12"))))
     (setnu-line-number-face ((t (:background "Grey15" :foreground "White" :bold t))))
     (show-paren-match-face ((t (:background "grey30"))))
     ;;(region ((t (:background "grey15"))))
     (region ((t (:background "slategray"))))
     (highlight ((t (:background "blue"))))
     (secondary-selection ((t (:background "navy"))))
     (widget-field-face ((t (:background "navy"))))
     (widget-single-line-field-face ((t (:background "royalblue")))))) )
